import nodemailer from "nodemailer";

const transporter = nodemailer.createTransport({
  service: "gmail",
  auth: {
    user: "3headedm@gmail.com",
    pass: "xlscicjddqyqcjiu",
  },
});

const report = `
Stone AI — Go-Live Status Report
Generated: ${new Date().toISOString()}
═══════════════════════════════════════════════════════════

COMPLETED ✓
───────────────────────────────────────────────────────────
 ✓  Clerk keys swapped to live (pk_live_, sk_live_)
 ✓  Clerk webhook secret configured
 ✓  Stripe keys swapped to live (pk_live_, sk_live_)
 ✓  Stripe webhook secret configured (whsec_)
 ✓  5 Stripe products created (Builder, Growth, Executive, Reseller, Enterprise)
 ✓  14 recurring prices created (monthly, 6-month, annual, promo)
 ✓  1 coupon created (First Month Deal — $10 off)
 ✓  2 promo prices created (Founder $14.99/mo, Early Adopter $39.99/mo)
 ✓  All price IDs updated in .env, .env.vercel, and Vercel dashboard
 ✓  Old test price IDs removed
 ✓  Old 6-month prices removed for Executive & Reseller
 ✓  STRIPE_UPGRADE_COUPON_ID removed (not on site)
 ✓  DATABASE_URL SSL upgraded to verify-full
 ✓  NEXT_PUBLIC_APP_URL set to https://stone-ai.net (Vercel)
 ✓  No hardcoded test keys found in codebase
 ✓  Production deployed to Vercel successfully
 ✓  Build passed — 69 pages generated, all routes operational

STRIPE PRODUCTS CREATED (LIVE)
───────────────────────────────────────────────────────────
Builder Plan
  Monthly:    $19.99/mo   (price_1T9wIOPYFII24ybVUeB84oir)
  6-Month:    $107.94/6mo (price_1T9wIOPYFII24ybV0HIFQ2nH)
  Annual:     $191.88/yr  (price_1T9wIOPYFII24ybVsk8jYSzA)
  Founder:    $14.99/mo   (price_1T9wIOPYFII24ybVYiQSYwdC)

Growth Plan
  Monthly:    $49.99/mo   (price_1T9wIPPYFII24ybVIye0z8A1)
  6-Month:    $269.94/6mo (price_1T9wIPPYFII24ybVvcfqh20G)
  Annual:     $479.88/yr  (price_1T9wIPPYFII24ybVDU0J7PJy)
  Early Adopter: $39.99/mo (price_1T9wIQPYFII24ybVYCtczhc3)

Executive Plan
  Monthly:    $99.99/mo   (price_1T9wIQPYFII24ybVfgOGDShn)
  Annual:     $959.88/yr  (price_1T9wIQPYFII24ybVvyayPEkR)

Reseller Plan
  Monthly:    $200/mo     (price_1T9wIRPYFII24ybV4yGOP2ur)
  Annual:     $2,040/yr   (price_1T9wIRPYFII24ybV0xsiEjFJ)

Enterprise Plan
  Monthly:    $500/mo     (price_1T9wISPYFII24ybVWN7V6FJH)
  Annual:     $5,700/yr   (price_1T9wISPYFII24ybVExes8eVM)

Coupon: First Month Deal — $10 off (ULGA8R6q)

STILL NEEDS ATTENTION
───────────────────────────────────────────────────────────
 ⚠  First Month coupon created in Stripe but not yet wired
    into the checkout route code. Customers can still use it
    manually if shared as a promo code.

 ℹ  Enterprise tier is display-only (no DB enum). This is
    fine if Enterprise is contact-sales only. If you want
    self-serve Enterprise checkout, it needs a DB migration.

 ℹ  Vercel needs a redeploy to pick up CLERK_WEBHOOK_SECRET
    (just added).

DEPLOYMENT
───────────────────────────────────────────────────────────
Live URL:  https://stone-ai.net
Vercel:    https://vercel.com/stonefreight2017-sources-projects/stone-ai
Deployed:  ${new Date().toISOString()}

═══════════════════════════════════════════════════════════
Report generated by Claude Code
`;

await transporter.sendMail({
  from: "Stone AI <3headedm@gmail.com>",
  to: "3headedm@gmail.com",
  subject: "Stone AI — Go-Live Status Report (March 11, 2026)",
  text: report,
});

console.log("Report sent to 3headedm@gmail.com");
