@echo off
echo Starting Stone AI Platform...
echo Starting vLLM...
start "vLLM" cmd /c "cd C:\Users\admin && vllm serve Qwen/Qwen3-32B-AWQ --port 8000"
timeout /t 10
echo Starting Next.js...
start "NextJS" cmd /c "cd C:\Users\admin\stone-ai && npm run dev"
timeout /t 5
echo Starting Watchdog...
start "Watchdog" cmd /c "cd C:\Users\admin\stone-ai && npx tsx scripts/watchdog.ts"
echo All services started.
